# Generated by Django 4.2.2 on 2024-01-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
