# Generated by Django 4.2.2 on 2023-12-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['author__last_name', 'title'], 'verbose_name': 'Bookington', 'verbose_name_plural': 'Bookington sss'},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='catalog_boo_title_5b6232_idx'),
        ),
    ]
