# Generated by Django 4.2.2 on 2024-01-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_options_book_catalog_boo_title_5b6232_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
